language: java
branches:
  only:
  - deploy
before_install:
- chmod +x gradlew
- openssl aes-256-cbc -K $encrypted_f0572fcf58ff_key -iv $encrypted_f0572fcf58ff_iv -in secretfile.tar.enc -out secretfile.tar -d
- "tar -xvf secretfile.tar -C $HOME/src/main/resources"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - lastvirgo266@gmail.com
