language: java
branches:
  only:
  - deploy
before_install:
- chmod +x gradlew
- openssl aes-256-cbc -K $encrypted_f0572fcf58ff_key -iv $encrypted_f0572fcf58ff_iv -in secretfile.tar.enc -out secretfile.tar -d
- ls
- sudo mkdir -p /src/main/resources
- sudo tar -xvf secretfile.tar -C /src/main/resources
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

after_failure :
- ls

notifications:
  email:
    recipients:
    - lastvirgo266@gmail.com
