language: java
branches:
  only:
  - deploy
before_install:
- chmod +x gradlew
- tar xvf secret.tar -C /src/main/resources
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - lastvirgo266@gmail.com
