language: java
jdk:
- openjdk8
branches:
  only:
  - master
before_install:
- chmod +x gradlew
- openssl aes-256-cbc -K $encrypted_e558ecafaec6_key -iv $encrypted_e558ecafaec6_iv -in properties.tar.enc -out properties.tar -d
- ls
- tar -xvf properties.tar -C src/main/resources
- ls src/main/resources
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"

after_failure :
- ls src/main/resources
- cat /home/travis/build/lastvirgo266/Project-CantRemember_API-Server/build/reports/tests/test/index.html

notifications:
  email:
    recipients:
    - lastvirgo266@gmail.com
