language: java
branches:
  only:
  - deploy
before_install:
- chmod +x gradlew
- openssl aes-256-cbc -K $encrypted_2895d60e3414_key -iv $encrypted_2895d60e3414_iv
  -in secret.tar.enc -out secret.tar -d
- tar xvf secret.tar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
notifications:
  email:
    recipients:
    - lastvirgo266@gmail.com
